//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEcommerc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECOMMERCEEntities : DbContext
    {
        public ECOMMERCEEntities()
            : base("name=ECOMMERCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mstr_Login> Mstr_Login { get; set; }
        public virtual DbSet<Mstr_categories> Mstr_categories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<CartsItem> CartsItems { get; set; }
        public virtual DbSet<Customer_Info> Customer_Info { get; set; }
        public virtual DbSet<Mstr_Cus_Add> Mstr_Cus_Add { get; set; }
        public virtual DbSet<Order_Items> Order_Items { get; set; }
        public virtual DbSet<Order_Tbl> Order_Tbl { get; set; }
    }
}
