//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEcommerc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Cus_Add
    {
        public int id { get; set; }
        public Nullable<int> cusId { get; set; }
        public string busi { get; set; }
        public Nullable<long> zip { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string add2 { get; set; }
        public string add1 { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Crd { get; set; }
        public Nullable<int> Crdby { get; set; }
        public Nullable<System.DateTime> Lmd { get; set; }
        public Nullable<int> LmdBy { get; set; }
    }
}
