//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEcommerc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_categories
    {
        public int Id { get; set; }
        public Nullable<int> Pid { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Crd { get; set; }
        public Nullable<int> Crdby { get; set; }
        public Nullable<System.DateTime> Lmd { get; set; }
        public Nullable<int> LmdBy { get; set; }
    }
}
