//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEcommerc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Login
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Crd { get; set; }
        public Nullable<int> CrdBy { get; set; }
        public Nullable<System.DateTime> Lmd { get; set; }
        public Nullable<int> LmdBy { get; set; }
    }
}
