//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEcommerc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Tbl
    {
        public int OrderID { get; set; }
        public string Image { get; set; }
        public string Customer { get; set; }
        public Nullable<System.DateTime> DateTIme { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<long> Amount { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> Crd { get; set; }
        public Nullable<int> Crdby { get; set; }
        public Nullable<System.DateTime> Lmd { get; set; }
        public Nullable<int> LmdBy { get; set; }
    }
}
